### ISSUE TITLE
Switch the host

### ISSUE THREAD

**Issue by johannsell** [Viva-con-Agua/dispenser#26]
For development, we have to consider microservices using different ports or in general different hosts. Currently, dispenser generates links with the same host as dispenser is running on.

**Comment by johannsell** [comment]
e.g. `localhost:9100` is used by Drops, while `localhost:4100` is used by Dispenser.

**Comment by deinelieblings** [comment]
you can currently do this with `dispenser.hostURL="http ..."` in the config files
