### ISSUE TITLE
Footer should be fixed

### ISSUE THREAD

**Issue by johannsell** [Viva-con-Agua/dispenser#42]
If the page content does not use the whole display space, the footer's bottom line should be fixed to the bottom of the display space. Use CSS `display: flex;` to fix the issue.

**Comment by deinelieblings** [comment]
the bug  ist fixed by https://github.com/Viva-con-Agua/dispenser/commit/f2d137d6d940d8aca251e69063606a151db3d29e

**Comment by johannsell** [comment]
Don't use `position: relative`. A modern browser should be able to use 
```
body {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
}
```
